---
title: "fairness"
author: "Bohao Tang"
date: "September 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
library(ica)

set.seed(11)

nobs = 500
s1c = icasamp("a","rnd",nobs)
s2c = icasamp("b","rnd",nobs)
s3c = icasamp("c","rnd",nobs)
s4c = icasamp("d","rnd",nobs)
s5c = icasamp("e","rnd",nobs)

s2 = cos(s2c)
s3 = sin(s2c)
Amat <- cbind(s1c, s2, s3, s4c)
Bmat <- matrix(2*runif(16),4,4)
Xmat <- tcrossprod(Amat,Bmat)

imod <- icafast(Xmat,4)
cor(Amat,imod$S)

s2 = sinh(s2c^2 + s3c)
s3 = s2c * s3c
s4 = cos(s4c) - s5c^2
s5 = s4c * s5c
Amat <- cbind(s1c, s2, s3, s4, s5)
Bmat <- matrix(2*runif(25),5,5)
Xmat <- tcrossprod(Amat,Bmat)

imod <- icafast(Xmat,5)
cor(Amat,imod$S)

imod <- icafast(Xmat,3)
cor(Amat,imod$S)
```


```{r randf, message=F}
library(randomForest)
library(readxl)
library(whitening)

credit.data <- read_excel("../data/credit_default.xls", skip = 1)
credit = credit.data[c(-1,-3,-25)]
sex = credit.data[3]
sex$SEX = factor(sex$SEX)
default = credit.data[25]
default$`default payment next month` = factor(default$`default payment next month`)

set.seed(71)

summary.rf = function(credit, default, sex, ntree=20){
    n0 = dim(credit)[1]
    indexes = sample(1:n0, size = 0.7*n0)
    
    credit.rf = randomForest(credit[indexes,], default[[1]][indexes], importance=TRUE, proximity=TRUE, ntree = ntree)
    predicted = predict(credit.rf, credit[-indexes,])
    sex.test = sex[-indexes,]
    default.test = default[[1]][-indexes]
    
    test.accuracy = sum(default.test == predicted) / length(predicted)
    
    sex_index = (sex.test == 1)
    bias = sum(predicted[sex_index] == 1) / length(predicted[sex_index]) - sum(predicted[1-sex_index] == 1) / length(predicted[1-sex_index])
    
    list(accuracy = test.accuracy, bias = bias)
}

original = summary.rf(credit, default, sex)

credit.white = whiten(as.matrix(credit), method = "PCA")
whitened = summary.rf(credit = credit.white, default, sex)

beta = glm(SEX~., data = cbind(credit.white, sex), family = "binomial")$coefficients
nb = length(beta)
beta = matrix(beta[2:nb], nb-1, 1)
# Orthognal Complement
B <- qr.Q(qr(beta),complete=TRUE)[,2:(nb-1)]
dim(B)

credit.orth = credit.white %*% B
dim(credit.orth)

orthognal = summary.rf(credit.orth, default, sex)


credit.ica5 = icafast(credit.orth,5)$S
credit.ica10 = icafast(credit.orth,10)$S
credit.ica15 = icafast(credit.orth,15)$S

ica5 = summary.rf(credit.ica5, default, sex)
ica10 = summary.rf(credit.ica10, default, sex)
ica15 = summary.rf(credit.ica15, default, sex)

pca5 = summary.rf(credit.orth[,1:5], default, sex)
pca10 = summary.rf(credit.orth[,1:10], default, sex)
pca15 = summary.rf(credit.orth[,1:15], default, sex)

accuracy = c(original$accuracy, whitened$accuracy, orthognal$accuracy, ica5$accuracy, ica10$accuracy, ica15$accuracy, pca5$accuracy, pca10$accuracy, pca15$accuracy)
bias = c(original$bias, whitened$bias, orthognal$bias, ica5$bias, ica10$bias, ica15$bias, pca5$bias, pca10$bias, pca15$bias)
rnames = c("original", "whitened", "orthognal", "ica5", "ica10", "ica15", "pca5", "pca10", "pca15")

summ = data.frame("acc" = accuracy, "bias" = bias, row.names = rnames)
summ
```
